# Generated by Django 3.0.2 on 2020-02-04 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.Categories'),
        ),
    ]
