# Generated by Django 3.0.2 on 2020-02-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_newsblog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsblog',
            name='date',
        ),
        migrations.AddField(
            model_name='newsblog',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
