# Generated by Django 3.0.2 on 2020-02-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200204_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsblog',
            name='category',
        ),
    ]
